# Generated by Django 5.0 on 2024-05-15 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BodyFreakApp', '0003_diet_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('muscle_group', models.CharField(max_length=100)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyFreakApp.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyFreakApp.diet')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BodyFreakApp.exercises')),
            ],
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
